# Generated by Django 4.1.2 on 2022-10-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img256', models.FileField(upload_to='')),
                ('img126', models.FileField(upload_to='')),
                ('img512', models.FileField(upload_to='')),
                ('name', models.CharField(blank=True, max_length=123, null=True)),
                ('seo_context', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
