# Generated by Django 4.1.2 on 2022-10-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img126',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img256',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img512',
            field=models.FileField(upload_to='upload/'),
        ),
    ]
