# Generated by Django 4.1.2 on 2022-10-08 19:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desciption', ckeditor.fields.RichTextField()),
                ('seo_text', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('publish_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('is_draft', models.BooleanField(default=True)),
            ],
        ),
    ]
