# Generated by Django 4.1.2 on 2023-05-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_news',
            field=models.BooleanField(default=False),
        ),
    ]
