# Generated by Django 4.1.2 on 2023-05-29 19:26

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_is_news'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('newsobject', django.db.models.manager.Manager()),
            ],
        ),
    ]
